apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-headless
  labels:
    purpose: efsdynamicdemo
    project: roboshop
spec:
  clusterIP: None # headless service (REQUIRED for StatefulSet)
  selector:
    purpose: efsdynamicdemo
    project: roboshop
  ports:
    - port: 80
      name: web
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-normal
  labels:
    purpose: efsdynamicdemo
    project: roboshop
spec:
  selector:
    purpose: efsdynamicdemo
    project: roboshop
  ports:
    - port: 80
      name: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  serviceName: nginx-svc-headless # MUST point to headless service
  replicas: 3
  selector:
    matchLabels:
      purpose: efsdynamicdemo
      project: roboshop
  template:
    metadata:
      labels:
        purpose: efsdynamicdemo
        project: roboshop
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
        labels:
          purpose: efsdynamicdemo
          project: roboshop
      spec:
        accessModes:
          - ReadWriteMany # ✅ FIXED (EFS requires RWX)
        storageClassName: roboshop-efs
        resources:
          requests:
            storage: 2Gi # required but not enforced by EFS
