apiVersion: v1
kind: Pod
metadata:
  name: roboshop_annotations
  namespace: default
  labels:
    app: appi
  annotations:
    project-name: new_project
spec:
  containers:
  - name: newnginx
    image: nginx