apiVersion: v1
kind: Pod
metadata:
  name: roboshop
  labels:
    project: roboshop-project
    purpose: Multicontainer demo
spec:
  containers:
    - name: nginx
      image: nginx

    - name: almalinux
      image: almalinux:9
