apiVersion: app/v1
kind: Deployment
metadata: 
  name: newdeployment
  labels:
    name: npexampleservice
    tier: backend
    reason: productdisplay
  
spec:
  replicas: 3

  selector:
    matchLabels:
      name: npexampleservice
      tier: backend
      reason: productdisplay
      
  template:
    metadata:
      labels:
        name: npexampleservice
        tier: backend
        reason: productdisplay
      spec:
        containers:
          - name: nginx
            image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: npserviceexample
  labels:
    purpose: npnewserviceexample
spec:
  type: LoadBalancer
  selector:
    name: npexampleservice
    tier: backend
    reason: productdisplay
  port:
    - protocol: TCP
      port: 80
      targetport: 80
