apiVersion: apps/v1
kind: Deployment
metadata:
  name: newdeployment
  labels:
    name: npexampleservice
    tier: backend
    reason: productdisplay
spec:
  replicas: 3
  selector:
    matchLabels:
      name: npexampleservice
      tier: backend
      reason: productdisplay
  template:
    metadata:
      labels:
        name: npexampleservice
        tier: backend
        reason: productdisplay
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: npserviceexample
  labels:
    purpose: npnewserviceexample
spec:
  type: LoadBalancer
  selector:
    name: npexampleservice
    tier: backend
    reason: productdisplay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
